name: Update YouTube Link on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  update-link:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update index.html with new YouTube link from issue
      run: |
        LINK=$(cat $GITHUB_EVENT_PATH | jq -r '.issue.body' | grep 'link:' | awk '{print $2}')
        sed -i "s#https://www.youtube.com/embed/[^?]*?#$LINK?#g" index.html

    - name: Commit and push if there are changes
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'github-action@users.noreply.github.com'
        git add index.html
        git diff --quiet && git diff --staged --quiet || git commit -m "Updated YouTube link from Issue"
        git push

    - name: Disable workflow cron schedule
      run: |
        sed -i 's/cron: .*/# cron schedule disabled/g' .github/workflows/update-youtube-link.yml
        git config user.name 'GitHub Action'
        git config user.email 'github-action@users.noreply.github.com'
        git commit -am "Disable cron schedule after run"
        git push
